### PR TITLE
[T-6563][16.0][ADD] sale_order_line_multi_warehouse_widget: show stock per warehouse in so lines

### PR DESCRIPTION
**Pull request by manuelregidor**
@ValentinVinagre @HaraldPanten 

@luis-ron Could you review?

### CODE REVIEW

**Comment by HaraldPanten** [comment]
@manuelregidor this PR is related to this comment from Enric, right?

https://github.com/OCA/sale-workflow/pull/3357#pullrequestreview-2369608417

**Comment by ValentinVinagre** [comment]
> @manuelregidor this PR is related to this comment from Enric, right?
> 
> [OCA/sale-workflow#3357 (review)](https://github.com/OCA/sale-workflow/pull/3357#pullrequestreview-2369608417)

yep, this will stay in our repository for now, we were already planning to separate it.

**Comment by manuelregidor** [comment]
@HaraldPanten Nope, Enric was talking about a different widget. The widget he's talking about is the one I mention in the Roadmap (https://github.com/OCA/sale-workflow/pull/3357/files#diff-5597e44ade31b1bbb8a22b56fdd4abbb1b3721c673e7d0a7d5377536cdf931f2), which would be used to select the quantity taken from each warehouse in a sale order line. The widget in this PR shows the availability of a product in each warehouse.

**Review by luis-ron — APPROVED** [review]
Functional review: LGTM 👍🏻

**Comment by ValentinVinagre** [comment]
> @HaraldPanten Nope, Enric was talking about a different widget. The widget he's talking about is the one I mention in the Roadmap (https://github.com/OCA/sale-workflow/pull/3357/files#diff-5597e44ade31b1bbb8a22b56fdd4abbb1b3721c673e7d0a7d5377536cdf931f2), which would be used to select the quantity taken from each warehouse in a sale order line. The widget in this PR shows the availability of a product in each warehouse.

Ahhh, I had understood that this widget was being referred to. They are different things:
* widget for warehouse stock: this functionality is provided by this module.
* widget for distribution of products by warehouse: this would mean creating a widget like the analytical distribution in invoices instead of the current wizard. But it is an improvement that will take a long time and is not currently contemplated.

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
